### ISSUE TITLE
memcmp tests fail to catch errors

### ISSUE THREAD

**Issue by JustinTArthur** [rbCabral/SHA-3#1]
Only the first digest in all of the 2M or 4M tests is equal in both the readable and SIMD implementations. The other digests are not equal, but still show as passing the tests. The `if ((memcmp(md[0],md1[0],32) && memcmp(md[1],md1[1],32)…) != 0` check for errors will only hit if every memcmp failed. Maybe you meant `||`  here instead of `&&`?

Is there a new copy of this code that will correctly fill in all digests? Thanks!

**Comment by rbCabral** [comment]
Thanks for your comment. I fixed this problem and updated the code. If you find other bug, please, let me know. Thanks!

**Comment by JustinTArthur** [comment]
59ecdaff5a056992976d5c5d7d5336c8366f806c fixed it. That was fast. I like seeing the entire hash process in one place as opposed to having to piece it together from the Keccak Code Package, so thanks for publishing your versions.
